### ISSUE TITLE
專案圖示建議

### ISSUE THREAD

**Issue by DOFILAB** [cocoaheadskaohsiung/The_Swift_Programming_Language_zh-TW#5]
附上個人修改的專案圖示，請管理者參考

（個人建議）

![home-hero-swift-hero_tw](https://cloud.githubusercontent.com/assets/5219977/3336658/11c16e7c-f837-11e3-8dcc-3b7466238408.png)

**Comment by Mikimoto** [comment]
感謝，已經請美工製作封面 ^^
